name: Backup Git Repository

on:
  push:
    branches:
    - master

jobs:
  git-repo-backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: git-repo-backup
      uses: jenkins-zh/git-backup-actions@v0.0.1
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        TARGET_GIT: "https://git@gitee.com:Fetchinator7/Video-Upload-Editor-Backup.git"